/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py a&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py b&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py c&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py d&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py e&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py f&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py g&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py h&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py i&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py j&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py k&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py l&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py m&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py n&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py o&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py p&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py q&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py r&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py s&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py t&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py u&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py v&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py w&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py x&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py y&
/opt/homebrew/bin/python3 /Users/kirangrandhi/fincity/pageai/scraping_site_lists/site_list_jasminedirectory.py z&
